name: Publish

on:
  push:
    branches:
      - master
    paths:
      - "Panda"
      - "patches/api/*.patch"
      - "patches/server/*.patch"
      - "patches/SpecialSource/*.patch"
      - "patches/SpecialSource2/*.patch"
      - "SpecialSource"
      - "SpecialSource2"
      - ".gitmodules"
      - "*.sh"
      - "pom.xml"
      - "settings.xml"
      - "!.idea"
      - "!.gitignore"
      - "!LICENSE"
      - "!README.md"
  workflow_dispatch:


permissions:
  contents: read
  packages: write

defaults:
  run:
    shell: bash

jobs:
  apijar:
    name: Publish API jar
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: ./tmp
          key: ${{ runner.os }}-tmp-${{ github.repository }}
          restore-keys: |
            ${{ runner.os }}-tmp-

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.7

      - name: Setup Spigot
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          ./apply.sh

      - name: Publish
        env:
          MAVEN_TOKEN: ${{ github.token }}
        run: ./publish.sh

      - name: Upload artifacts
        uses: CrimsonGiteaActions/upload-artifact@main
        if: ${{ always() }}
        with:
          name: ColosseumSpigot-API-${{ github.run_id }}
          path: ./ColosseumSpigot-API/target/*.jar
          overwrite: true
          retention-days: 7
        continue-on-error: true
